describe("navigation test", () => {
  it("passes", () => {
    cy.visit("/")
    cy.get('[data-id="open-sidebar-button"]').wait(1000).click()
    cy.get('[data-id="open-sidebar-content"]').should("be.visible")
    cy.get('[data-id="close-sidebar-button"]').click()
    cy.get('[data-id="open-sidebar-content"]').should("not.visible")
    cy.get('[data-id="theme-toggle"]').should("be.visible").click()
    cy.get('[data-id="theme-toggle"]').wait(1000).should("be.visible").click()
    cy.get('[data-id="delete-history-button"]').click()
    cy.get('[data-id="delete-history-content"]').should("be.visible").wait(1000)
    cy.get('[data-id="delete-history-confirm"]').click().wait(1000).click()
    cy.get('[data-id="delete-history-confirm"]').should("not.checked")
    cy.get('[data-id="close-delete-history-button"]').click()
  })
})
